In [1]:
import pandas as pd

In [2]:
#Data preview
test = pd.read_csv('..\\test_data.csv')
test

,id,time,x,y,road_id,cus,roadDis
0,233f8acb569419f09cfa6fa6a43e0a58,1407453063000,116.446327,39.956349,164467,0,-1.00000
1,233f8acb569419f09cfa6fa6a43e0a58,1407454706000,116.449615,39.959800,170865,0,547.11751
2,233f8acb569419f09cfa6fa6a43e0a58,1407454766000,116.450998,39.959967,166270,0,220.25963
3,233f8acb569419f09cfa6fa6a43e0a58,1407454886000,116.447343,39.958201,164460,0,385.11362
4,233f8acb569419f09cfa6fa6a43e0a58,1407454946000,116.441692,39.961114,169177,0,633.31186
...,...,...,...,...,...,...,...
9995,32d042fb7e9d9e5223812035875000cb,1407458963000,116.265317,40.015669,200896,0,452.90522
9996,32d042fb7e9d9e5223812035875000cb,1407459023000,116.265364,40.012070,201992,0,401.34724
9997,32d042fb7e9d9e5223812035875000cb,1407459083000,116.265400,40.013629,201986,0,224.86207
9998,32d042fb7e9d9e5223812035875000cb,1407459143000,116.265118,40.019088,201565,0,607.18079
9999,32d042fb7e9d9e5223812035875000cb,1407459205000,116.270801,40.019715,203804,0,524.14073

In [3]:
#Trajectory extraction
test['od'] = 0
i = 0
x = 0
while i < len(test.index):
    try:
        if test.loc[0,'cus'] == 1:
            x += 1
        elif test.loc[i].values[5:6] == 0 and test.loc[i-1].values[5:6] == 1 and test.loc[i-2].values[5:6] == 1:
            test.loc[i-x, 'od'] = 1
            test.loc[i-1, 'od'] = 2
            x = 0
        elif test.loc[i].values[5:6] == 0:
            x = 0
        i += 1
    except Exception as e:
        i += 1