In [2]:
import pandas as pd

In [5]:
#The data calculated from CiteSpace
test = pd.read_csv('..\\Data\\test_20140808_1998.csv')
test.drop('Unnamed: 0', axis = 1, inplace = True)
test

      name  拥堵  交通量   中心性  爆发
0      万丰路  拥堵  低流量    无效  无效
1      万寿路  畅通  高流量  低中心性  无效
2     万泉河桥  畅通  高流量  高中心性  无效
3     万泉河路  畅通  高流量  高中心性  无效
4      万红路  畅通  低流量    无效  无效
..     ...  ..  ...   ...  ..
524   麦子店街  拥堵  高流量  低中心性  无效
525   黄寺大街  拥堵  高流量    无效  无效
526  鼓楼外大街  畅通  高流量  低中心性  无效
527  鼓楼西大街  拥堵  低流量    无效  爆发
528    龙水路  拥堵  低流量    无效  爆发

[529 rows x 5 columns]

In [7]:
#Road classes data preview
road = pd.read_csv('..\\Data\\test_road_class.txt', sep = ',')
road

      FuncClass PathName
0             5      福西街
1             5
2             5     聚源北路
3             3     Ｓ３３０
4             3     Ｘ０３０
...         ...      ...
8542          5     罗汉石路
8543          5     石塘峪路
8544          5     五坝地路
8545          5     刘家峪路
8546          5     水峪南路

[8547 rows x 2 columns]

In [10]:
#Road classes match roads
i = 0
j = 0
test['funclass'] = 0
while i < len(test.index):
    j = 0
    while j < len(road.index):
        if test.loc[i, 'funclass'] == 0:
            if test.loc[i, 'name'] == road.loc[j, 'PathName']:
                test.loc[i, 'funclass'] = road.loc[j, 'FuncClass']
                j = len(road.index)
        if test.loc[i, 'funclass'] != 0:
            j = len(road.index)
        j += 1
    i += 1

In [12]:
test.to_csv('..\\Data\\test_data_for_mining', encoding = 'utf-8-sig', index = False)